### ISSUE TITLE
Script preview colors are distorted in hourly build (1.8.0-58).

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#512]
Caught from testing a new script.

![borked preview colors](https://user-images.githubusercontent.com/35666439/61677178-8ec39900-accc-11e9-9dac-e94df0ec3275.png)

![borked preview colors 2](https://user-images.githubusercontent.com/35666439/61677454-b49d6d80-accd-11e9-92c2-762e1386195d.png)

**Comment by Wolfvak** [comment]
Hey, would you mind uploading the script you used for testing? thanks

**Comment by Wolfvak** [comment]
Actually nevermind, I think I just fixed it. Could you test the latest commit in `staging` and let me know if it is fixed?

**Comment by TurdPooCharger** [comment]
@Wolkvak, can you upload the test build here, please?

Homebrews almost never compile correctly on my main laptop as I could never manage to install a clean setup of devkitARM on Windows. My secondary laptop with Linux Mint died some months ago (would have installed Arch or Manjaro distro for that `pacman` support).

For reasons, I refuse to ever install anything Linux on the main computer. Tux the Penguin and I are not friends...

I understand activity at [d0k3.secretalgorithm.com](https://d0k3.secretalgorithm.com/) has slowed down. Congratulations on the new job, @d0k3. :-)

![make fail](https://user-images.githubusercontent.com/35666439/61766339-8ba0d980-adae-11e9-9a5e-0c8ca84e112d.png)

***

@Wolfvak, I don't mind sharing the script in private but would like to keep it under wraps as it's not quite ready yet. A public release of the worked on script might be too premature as there is a pair of script commands I'm reluctant to request later because their purpose might be too niche.

I was hoping to present a case for them if the polished version of script can demonstrate value and a definitive need for those (yet to be proposed) commands.

**Comment by Wolfvak** [comment]
[Here you go](https://github.com/d0k3/GodMode9/files/3426532/GM9-colorfix.zip).

Also that windows issue comes from having a horribly out of date gcc version, just remove anything related to mingw/msys/msys2 and use the devkitPro installer from scratch, it'll install msys2 for you alongside dkp-pacman.

**Comment by TurdPooCharger** [comment]
The preview colors stop being assigned the correct RGB values when other preview commands are involved:

- `set PREVIEW_MODE "FULL"`
- `set PREVIEW_MODE "$[GM9OUT]/example.png"`

![borked preview colors 3](https://user-images.githubusercontent.com/35666439/61829562-2fce6300-ae37-11e9-904b-093a897ca308.png)

Here's a gm9 test script that randomize colors for the preview's `_ACTIVE`, `_CODE`, and `_COMMENT` with image switching. In the v1.8.0 stable release, the output RGB values match against what's check in Photoshop color selector. Repeat iterations in v1.8.0-76 throws the colors off.

- [random colors test.zip](https://github.com/d0k3/GodMode9/files/3428820/random.colors.test.zip)

**Comment by Wolfvak** [comment]
With current versions, GM9 works on a 16-bit color space (RGB565) and all conversions from the original 24-bit color space obviously bring some data loss. I've tested your script and it matches the expected results pretty well.

For future reference, the low 3 bits of the red and blue channel are lost, and the low 2 bits of the green channel, this means colors will "skip" every 8 and 4 values per channel.

**Comment by TurdPooCharger** [comment]
I'm not sure how to process this info. Would that mean scripts previously coded with (RGB888) in mind would no longer be color accurate with future GodMode9 releases? On one hand, I don't know of any previous scripts that extensively utilized the preview color commands, so moving forward with the change might not be an issue in terms of maintaining legacy support.

If (RGB565) is the new standard, does this mean choosing a specific color is now written like this?

**Example,**

[RGB565 Color calculator](http://www.rinkydinkelectronics.com/calc_rgb565.php)
[Hexadecimal to Decimal converter](https://www.rapidtables.com/convert/number/hex-to-decimal.html)

Where:
0x0B = 11
0xD2 = 210
0x83 = 131

From:
- `set PREVIEW_MODE_ACTIVE "0BD283"`

To:
- `set PREVIEW_MODE_ACTIVE "0E90"`


Was the change from (RGB888) to (RGB565) made throughout GodMode9 or limited to scripting?
If I had to guess, the noticeably improved script performance was partially due to this change, yes?

**Comment by Wolfvak** [comment]
They won't be _perfectly_ color accurate with GM9, but the color will still be close enough. This change was done with performance in mind, since it simplifies pointer arithmetic and reduces the amount of writes (3 8-bit writes vs 1 16-bit write).

And no, there are routines in place to convert most of the old RGB888 buffers to RGB565. As a matter of fact, the initial reason for this bug is because I forgot to implement that routine in the scripting section (I'd only implemented it in UI and PNG routines).

You should keep using regular RRGGBB colors, but now 000000 and 000007 will be the exact same color, because some of the lower bits get stripped out.

I'm gonna close this now, since the issue has been fixed.

**Comment by TurdPooCharger** [comment]
My script's mass dump GBA VC saves instruction screen doesn't show up with red fonts on v1.8.0-76. I think something is still broken.

**Comment by Wolfvak** [comment]
So running `set PREVIEW_COLOR_ACTIVE FF0000` doesn't turn the active font red? What color is it?

**Comment by TurdPooCharger** [comment]
It might be better if you see the script firsthand. Can I PM you at GBAtemp?

**Comment by Wolfvak** [comment]
Sure, go for it.
